# docker-compose.yaml
# Build React (via your Dockerfile) -> Serve via Nginx -> Proxy /ws to Asterisk

#networks:
#  asterisk_common_net:
#    external: true
#
services:
  webrtc-ui:
    build:
      context: .                   # Dockerfile is in this directory
      dockerfile: Dockerfile
    container_name: webrtc-ui
    restart: unless-stopped
    ports:
      - "8080:80"                  # HTTP
      - "8443:443"                 # HTTPS
    volumes:
      - ./nginx/certs:/etc/nginx/certs
#   networks:
#     - asterisk_common_net
